# Generated by Django 2.0.2 on 2018-02-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('author', models.CharField(default='Zachary Faddis', max_length=30)),
                ('published', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
