# Generated by Django 2.0.3 on 2018-03-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180318_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='id',
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
