# Generated by Django 2.0.3 on 2018-04-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180320_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='text',
        ),
        migrations.AddField(
            model_name='article',
            name='htmlFile',
            field=models.FileField(default='helloWorld.html', upload_to=''),
        ),
    ]
